# Generated by Django 4.0.2 on 2022-03-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rooms_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
